### ISSUE TITLE
[Epic] EDPN Frontend Foundations

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#128]
This is just a tracker issue to be used for the first milestone. Most of the following have already been handled under other issues and some might need new issues which will be added to the same milestone. Just creating this to group the foundational work.

- [x] Header, Content & Footer Sections
- [x] Header & Side Navigation
- [x] Header Actions
- [x] Landing Page Layout
- [x] Localhost Development Setup
- [x] Development / Staging Stage Setup
- [ ] Production Stage Setup
- [x] Github Based Deployment for Development
- [ ] Github Based Deployment for Production
- [x] Website Analytics for Development Stage
- [ ] Website Analytics for Production Stage
