### ISSUE TITLE
[Epic] Trade Routes Search Feature

### ISSUE THREAD

**Issue by nitishdhar** [eddb2-0/EDDB-2.0-frontend#133]
- [ ] Find a direct route between two stations to sell a commodity for a profit.
- [ ] Find a loop (to and fro) route between two systems to sell commodities for a profit.
- [ ] Find a route comprised of several trades between stations along the route that lead to a know destination from a known starting point.

TBD..
